# Meskó Balázs <meskobalazs@gmail.com>, 2016. #zanata
# Meskó Balázs <meskobalazs@gmail.com>, 2018. #zanata
# Meskó Balázs <meskobalazs@gmail.com>, 2019. #zanata
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-11-03 21:47-0500\n"
"PO-Revision-Date: 2019-10-26 07:41+0000\n"
"Last-Translator: Meskó Balázs <meskobalazs@gmail.com>\n"
"Language-Team: Hungarian\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"X-Generator: Zanata 4.6.2\n"

#: ../plugins/showvars.py:46
msgid "show all active dnf variables"
msgstr "az összes aktív dnf változó megjelenítése"

#: ../plugins/torproxy.py:31
msgid "Disabling torproxy plugin: cannot connect to the Tor network"
msgstr ""
"A torproxy bővítmény letiltása: nem lehet a Tor hálózathoz kapcsolódni"

#: ../plugins/kickstart.py:60
msgid "Install packages defined in a kickstart file on your system"
msgstr "A kickstart fájlban megadott csomagok telepítése a rendszerre"

#: ../plugins/kickstart.py:65
msgid "kickstart file"
msgstr "kickstart fájl"

#: ../plugins/kickstart.py:83
#, python-format
msgid "file cannot be parsed: %s"
msgstr "a fájl nem dolgozható fel: %s"

#: ../plugins/rpm_conf.py:65
msgid "Adding '{}' to list of handling packages for rpmconf"
msgstr "A(z) „{}” hozzáadása a rpmconf kezelőcsomagjaihoz"

#: ../plugins/rpm_conf.py:71
msgid "rpmconf plugin will not run in non-interactive mode"
msgstr "az rpmconf bővítmény nem fog futni nem interaktív módban"

#: ../plugins/rpm_conf.py:84
msgid "ignoring sys.exit from rpmconf due to missing MERGE variable"
msgstr "a sys.exit mellőzése az rpmconfban a hiányzó MERGE változó miatt"

#: ../plugins/rpm_conf.py:88
msgid "ignoring sys.exit from rpmconf due to missing file"
msgstr "a sys.exit mellőzése az rpmconfban egy hiányzó fájl miatt"

#. Translators: This string is only used in unit tests.
#: ../plugins/system_upgrade.py:45
msgid "the color of the sky"
msgstr "az égbolt színe"

#: ../plugins/system_upgrade.py:61
msgid "Need a --releasever greater than the current system version."
msgstr ""
"A jelenlegi rendszer verziójánál nagyobb --releasever értéket kell megadnia."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:63
msgid ""
"Download complete! Use 'dnf system-upgrade reboot' to start the upgrade.\n"
"To remove cached metadata and transaction use 'dnf system-upgrade clean'"
msgstr ""
"Letöltés kész! Használja a „dnf system-update reboot” parancsot a frissítés megkezdéséhez.\n"
"A gyorsítótárazott metaadatok és tranzakciók eltávolításához használja a „dnf system-upgrade clean” parancsot"

#: ../plugins/system_upgrade.py:66
msgid "Sorry, you need to use 'download --releasever' instead of '--network'"
msgstr ""
"Sajnáljuk, a „download --releasever” parancsot kell használni a „--network” "
"helyett"

#: ../plugins/system_upgrade.py:119
#, python-format
msgid "Screen blanking can't be disabled: %s"
msgstr "A képernyő törlése nem tiltható le: %s"

#: ../plugins/system_upgrade.py:140
#, python-format
msgid "Failed loading state file: %s, continuing with empty state."
msgstr "Állapotfájl betöltése meghiúsult: %s, folytatás üres állapottal."

#: ../plugins/system_upgrade.py:277
msgid "The following boots appear to contain upgrade logs:"
msgstr "A következő indulások tartalmazzák a frissítési naplókat:"

#: ../plugins/system_upgrade.py:287
msgid "-- no logs were found --"
msgstr "-- nem található naplófájl --"

#: ../plugins/system_upgrade.py:302
msgid "Cannot find logs with this index."
msgstr "Ilyen index alatt nem található naplófájl."

#: ../plugins/system_upgrade.py:311
msgid "Unable to match systemd journal entry"
msgstr "Nincs találat a systemd naplóbejegyzésre"

#: ../plugins/system_upgrade.py:330
msgid "Prepare system for upgrade to a new release"
msgstr "Rendszer előkészítése az új verzióra történő frissítéshez"

#: ../plugins/system_upgrade.py:340
msgid "keep installed packages if the new release's version is older"
msgstr "megtartja a telepített csomagokat, ha az új kiadás verziója régebbi"

#: ../plugins/system_upgrade.py:344
msgid "which logs to show"
msgstr "megjelenítendő naplók"

#: ../plugins/system_upgrade.py:401
msgid "Additional information for System Upgrade: {}"
msgstr "További információk a rendszerfrissítéshez: {}"

#: ../plugins/system_upgrade.py:404
msgid ""
"Before you continue ensure that your system is fully upgraded by running "
"\"dnf --refresh upgrade\". Do you want to continue"
msgstr ""
"A folytatás előtt győződjön meg róla, hogy a rendszer teljesen frissítve "
"lett a „dnf --refresh upgrade” paranccsal. Folytatja"

#: ../plugins/system_upgrade.py:408
msgid "Operation aborted."
msgstr "Művelet megszakítva."

#: ../plugins/system_upgrade.py:472
msgid "system is not ready for upgrade"
msgstr "a rendszer nem áll készen a frissítésre"

#: ../plugins/system_upgrade.py:474
msgid "upgrade is already scheduled"
msgstr "a frissítés már ütemezve van"

#: ../plugins/system_upgrade.py:480
msgid "trigger file does not exist. exiting quietly."
msgstr "a kiváltó fájl nem létezik. csendes kilépés."

#: ../plugins/system_upgrade.py:483
msgid "another upgrade tool is running. exiting quietly."
msgstr "fut egy másik frissítési eszköz. csendes kilépés."

#. Translators: do not change "reboot" here
#: ../plugins/system_upgrade.py:489
msgid "use 'dnf system-upgrade reboot' to begin the upgrade"
msgstr "használja ezt: „dnf system-upgrade reboot” a frissítés megkezdéséhez"

#: ../plugins/system_upgrade.py:506
msgid "Rebooting to perform upgrade."
msgstr "Újraindítás a frissítés végrehajtásához."

#: ../plugins/system_upgrade.py:528 ../plugins/system_upgrade.py:534
msgid "Starting system upgrade. This will take a while."
msgstr "Rendszerfrissítés elkezdése. Ez eltart egy darabig."

#: ../plugins/system_upgrade.py:559 ../plugins/system_upgrade.py:568
#, python-format
msgid "Unable to match package: %s"
msgstr "Nincs találat a csomagra: %s"

#: ../plugins/system_upgrade.py:573
msgid "Unable to match some of packages"
msgstr "Nincs találat néhány csomagra"

#: ../plugins/system_upgrade.py:576
msgid "Cleaning up downloaded data..."
msgstr "Letöltött adatok tisztítása…"

#: ../plugins/system_upgrade.py:623
msgid "Download finished."
msgstr "Letöltés befejezve."

#: ../plugins/system_upgrade.py:627 ../plugins/system_upgrade.py:628
msgid "Upgrade complete! Cleaning up and rebooting..."
msgstr "Frissítés kész! Tisztítás és újraindítás…"

#: ../plugins/tracer.py:70
msgid "For more information run:"
msgstr "További információért futtassa:"

#: ../plugins/tracer.py:97
msgid "Call to Tracer API ended unexpectedly:"
msgstr "A Tracer API hívása váratlanul véget ért:"

#: ../plugins/tracer.py:99
msgid ""
"Please visit https://github.com/FrostyX/tracer/issues and submit the issue. "
"Thank you"
msgstr ""
"Keresse fel a https://github.com/FrostyX/tracer/issues oldalt, és küldje be "
"a problémát. Köszönjük"

#: ../plugins/tracer.py:101
msgid "We apologize for any inconvenience"
msgstr "Elnézést kérünk a kellemetlenségekért"

#: ../plugins/snapper.py:49
#, python-format
msgid "connect to snapperd failed: %s"
msgstr "a snapperdhez kapcsolódás sikertelen: %s"

#: ../plugins/snapper.py:55
msgid "creating pre_snapshot"
msgstr "művelet előtti pillanatfelvétel készítése"

#: ../plugins/snapper.py:61
#, python-format
msgid "created pre_snapshot %d"
msgstr "%d. művelet előtti pillanatfelvétel elkészült"

#: ../plugins/snapper.py:65
#, python-format
msgid "creating pre_snapshot failed: %s"
msgstr "A művelet előtti pillanatfelvétel készítése meghiúsult: %s"

#: ../plugins/snapper.py:74
msgid "skipping post_snapshot because creation of pre_snapshot failed"
msgstr ""
"művelet utáni pillanatfelvétel kihagyása, mert az előtti készítése "
"meghiúsult"

#: ../plugins/snapper.py:80
msgid "creating post_snapshot"
msgstr "művelet utáni pillanatfelvétel készítése"

#: ../plugins/snapper.py:85
#, python-format
msgid "created post_snapshot %d"
msgstr "%d. művelet utáni pillanatfelvétel elkészült"

#: ../plugins/snapper.py:89
#, python-format
msgid "creating post_snapshot failed: %s"
msgstr "A művelet utáni pillanatfelvétel készítése meghiúsult: %s"
